print("statement 1")
print("statement 2")
if True: 
    print("True statement1")
    print("True statement2")
    print("True statement3")
    print("True statement4")
print("statement 3")
print("statement 4")
